//
// API ENDPOINTS USER
//

// HÄMTA ALLA USERS // SKICKA INTE MED LÖSENORD // BARA ID, NAMN + EMAIL PÅ ALLA USERS
# @name getUsers
GET http://localhost:3000/api/users

###

// HÄMTA SPECIFIK USER // SKICKA HELA OBJEKTET
POST http://localhost:3000/api/users/
Content-Type: application/json

{
  "id": "// EN USER ID"
}

###

// SKAPA USER
POST http://localhost:3000/api/users/add
Content-Type: application/json

{
  "name": "Youssef",
  "email": "youssef@mail.com",
  "password": "test"
}

###

// LOGGA IN USER
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "email": "youssef@mail.com",
  "password": "test"
}

###

//
// API ENDPOINTS PRODUKTER
//

// HÄMTA ALLA PRODUKTER

# @name getProducts
GET http://localhost:3000/api/products

###

// HÄMTA SPECIFIK PRODUKT
GET http://localhost:3000/api/products/641a2a6abfdb2510dc1c1b27

###

// SKAPA PRODUKT
POST http://localhost:3000/api/products/add
Content-Type: application/json

{
  "name": "Sail Racing",
  "description": "Jacka",
  "price": 1400, 
  "lager": 8
}

###

//
// API ENDPOINTS ORDERS
//

// SKAPA ORDER FÖR EN SPECIFIK USER // PRODUCTS ÄR EN ARRAY MOTSVARANDE INNEHÅLLET I KUNDVAGN
POST http://localhost:3000/api/orders/add
Content-Type: application/json

{
  "user": "641b7a4896d32b133b71f525",
      "products": [
    {
      "productId": "641a2dc6608516b3f9eef5aa",
      "quantity": 3
    },
    {
      "productId": "641a2e05608516b3f9eef5ac",
      "quantity": 1
    }
  ]
}

###


// HÄMTA ALLA ORDERS
GET http://localhost:3000/api/orders/all/

###